name: Test Vars Context Test
run-name: RUN Vars Context Test

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello JOB_NAME"
        run: |
          echo "JOB_NAME from vars context: ${{ vars.JOB_NAME }}"
